### PR TITLE
bug/suffix spacing issue

### PR DESCRIPTION
**Pull request by Gnzlt**
## What does this implement/fix? Explain your changes.
- [T1319754](https://testrail.systems.mega.nz/index.php?/tests/view/1319754)
- [AND-12768](https://jira.developers.mega.co.nz/browse/AND-12768)

## Any relevant logs, error output, etc?
...

## Any other comments?
...

## Where has this been tested?

- **Devices/Simulators:** 
Google Pixel 4

- **OS Version:** 
Android 11

### CODE REVIEW

**Comment by Piasy** [comment]
Hi @Gnzlt  the original issues are fixed, but when I input a very long file name, the suffix isn't visible anymore, is that expected?

**Comment by Gnzlt** [comment]
> Hi @Gnzlt the original issues are fixed, but when I input a very long file name, the suffix isn't visible anymore, is that expected?

It can be expected since it's being drawn right after the original text and is intended to not be selectable.

**Comment by Piasy** [comment]
Okay, then I'll approve this PR.

**Review by Piasy — APPROVED** [review]

**Review by javiergm1983 — APPROVED** [review]
Reviewed and tested. Code changes look fine and the issues have been solved.

**Pull request merged**
